/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/parghii.glb 
*/

import React, { useEffect } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'
import { animated, useSpring} from '@react-spring/three';
import * as THREE from 'three'

// Custom material that always renders on top
export const alwaysOnTopMaterial = new THREE.MeshStandardMaterial({
  color: '#ffffff',
  depthTest: false,
  depthWrite: false,
  polygonOffset: true,
  polygonOffsetFactor: -4,
  transparent: true,
  opacity: 1,
})
alwaysOnTopMaterial.onBeforeCompile = shader => {
  shader.depthTest = false
  shader.depthWrite = false
}

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('./models/parghii.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  // Replace 'TEXT' material with alwaysOnTopMaterial
  if (materials && materials.TEXT) {
    materials.TEXT = alwaysOnTopMaterial;
  }
  const { actions, names} = useAnimations(animations, group)

  const currentPage = props.currentPage || 0;
  const s3_1_ElapsedTime = props.s3_1_ElapsedTime || 0;
  const animationsSpeed = .5;
  const triggerVarfuri = props.triggerVarfuri || 0;
  const triggerGreutate = props.triggerGreutate || 0;
  const triggerAruncare = props.triggerAruncare || 0;
  const postura = props.postura || 0;

  useEffect(() => {
    const action = actions['S3_2_Animation'];
    if (action) {
      action.reset(); // Ensure animation starts from the beginning
      action.setLoop(THREE.LoopOnce, 1);
      action.clampWhenFinished = true;
      action.setEffectiveTimeScale(1);
      action.play();
    }
  }, [triggerVarfuri])

  useEffect(() => {
    const action = actions['S6_Animation_2'];
    if (action) {
      action.reset(); // Ensure animation starts from the beginning
      action.setLoop(THREE.LoopOnce, 1);
      action.clampWhenFinished = true;
      action.setEffectiveTimeScale(1.5);
      action.play();
    }

    const action2 = actions['S6_Bulger_Animation'];
    if (action2) {
      action2.reset(); // Ensure animation starts from the beginning
      action2.setLoop(THREE.LoopOnce, 1);
      action2.clampWhenFinished = true;
      action2.setEffectiveTimeScale(1.5);
      action2.play();
    }

  }, [triggerAruncare])

  useEffect(() => {
    const action = actions['S2_Animation.001'];
    if (action) {
      action.reset(); // Ensure animation starts from the beginning
      action.setLoop(THREE.LoopOnce, 1);
      action.clampWhenFinished = true;
      action.setEffectiveTimeScale(.25);
      action.play();
    }
  }, [triggerGreutate])

  useEffect(() => {
    const s3Action = actions['S7_Action'];
    if (s3Action) {
      const duration = s3Action.getClip().duration;
      const time = (postura) % duration;
      s3Action.time = time;
      s3Action.paused = true; // Pause the action to control time manually
    }
    console.log(s3Action.getClip().duration);
  }, [postura])

  useEffect(() => {
    const s3Action = actions['S3_1_Animation'];
    if (s3Action) {
      const duration = s3Action.getClip().duration;
      const time = (s3_1_ElapsedTime) % duration;
      s3Action.time = time;
      s3Action.paused = true; // Pause the action to control time manually
    }
    console.log(s3Action.getClip().duration);
  }, [s3_1_ElapsedTime])

  useEffect(() => {
    for (const action of Object.values(actions)) {
      action.setEffectiveTimeScale(.5);

      if(action.getClip().name !== 'S3_1_Animation' 
      || action.getClip().name !== 'S3_2_Animation'
      || action.getClip().name !== 'S7_Action'
      || action.getClip().name !== 'S2_Animation.001'
      || action.getClip().name !== 'S6_Animation_2'
      || action.getClip().name !== 'S6_Bulger_Animation'){
        action.play()
      }

      if(action.getClip().name === 'S3_1_Animation'){
        action.play()
        action.paused = true;
      }

      if(action.getClip().name === 'S6_Animation_2' || action.getClip().name === 'S6_Bulger_Animation'){
        action.setEffectiveTimeScale(1.5);
      }
    }
  }, [actions])

  const s1SpringData = useSpring({
    scale: currentPage === 2 || currentPage === 1 ? 1 : 0,
    config: { mass: 1, tension: 180, friction: 18 }
  });

  const s2SpringData = useSpring({
    scale: currentPage === 3 ? 1 : 0,
    config: { mass: 1, tension: 180, friction: 18 }
  });

  const s3_1_SpringData = useSpring({
    scale: currentPage === 4 ? 1 : 0,
    config: { mass: 1, tension: 180, friction: 18 }
  });

  const s3_2_SpringData = useSpring({
    scale: currentPage === 5 ? 1 : 0,
    config: { mass: 1, tension: 180, friction: 18 }
  });

  const s3_3_SpringData = useSpring({
    scale: currentPage === 6 ? 1 : 0,
    config: { mass: 1, tension: 180, friction: 18 }
  });

  const s4SpringData = useSpring({
    scale: currentPage === 7 ? 1 : 0,
    config: { mass: 1, tension: 180, friction: 18 }
  });

  const s5SpringData = useSpring({
    scale: currentPage === 8 || currentPage === 9 ? 1 : 0,
    config: { mass: 1, tension: 180, friction: 18 }
  });

  const s6SpringData = useSpring({
    scale: currentPage === 10 ? 1 : 0,
    config: { mass: 1, tension: 180, friction: 18 }
  });

  const s7SpringData = useSpring({
    scale: currentPage === 11 ? 1 : 0,
    config: { mass: 1, tension: 180, friction: 18 }
  });

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <animated.group name="S1_Group" position={[0, 0, 0]} scale={s1SpringData.scale}>
          <group name="S1_Human" position={[-0.871, 0, -0.785]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <primitive object={nodes.mixamorig1Hips} />
            <primitive object={nodes.elbowIKR} />
            <primitive object={nodes.elbowIKL} />
            <primitive object={nodes.handIKL} />
            <primitive object={nodes.handIKR} />
            <primitive object={nodes.headLookAt} />
            <primitive object={nodes.kneeIKL} />
            <primitive object={nodes.kneeIKR} />
            <primitive object={nodes.heelIKL} />
            <primitive object={nodes.heelIKR} />
            <primitive object={nodes.kneeIKL001} />
            <skinnedMesh name="s1humanmodel" geometry={nodes.s1humanmodel.geometry} material={materials.Human} skeleton={nodes.s1humanmodel.skeleton} />
          </group>
          <mesh name="Stand" geometry={nodes.Stand.geometry} material={materials.Metal} scale={0.362} />

          <gridHelper args={[10, 10]} />
          <mesh name="Plane" rotation={[-Math.PI / 2, 0, 0]} position={[0, -0.01, 0]} scale={5}>
            <planeGeometry args={[2, 2]} />
            <meshStandardMaterial color="#000000" />
          </mesh>

        </animated.group>

        <group scale={1} rotation={[0, Math.PI / -3, 0]} position={[0, 1, 0]}>
          <animated.group name="S2_Group" scale={s2SpringData.scale}>
            <group name="S2Armature" position={[-0.169, 0.972, -0.769]}>
              <primitive object={nodes.ArmTop} />
              <primitive object={nodes.ArmIK} />
              <primitive object={nodes.ElbowIK} />
              <group name="musclefibermodel">
                <skinnedMesh name="Cylinder004" geometry={nodes.Cylinder004.geometry} material={materials['Muscle no Texture']} skeleton={nodes.Cylinder004.skeleton} />
                <skinnedMesh name="Cylinder004_1" geometry={nodes.Cylinder004_1.geometry} material={materials['Muscle Inside']} skeleton={nodes.Cylinder004_1.skeleton} />
              </group>
            </group>
          </animated.group>
        </group>

        <group scale={4} rotation={[0, Math.PI / 9, 0]} position={[0, -.5, 0]} >
        <animated.group name="S3_1_Group" scale={s3_1_SpringData.scale}>
          <group name="s3_1_armature">
            <primitive object={nodes.Bone_1} />
            <group name="spinemodel">
              <skinnedMesh name="Cube009" geometry={nodes.Cube009.geometry} material={materials.Bone} skeleton={nodes.Cube009.skeleton} />
              <skinnedMesh name="Cube009_1" geometry={nodes.Cube009_1.geometry} material={materials.Spine_Between} skeleton={nodes.Cube009_1.skeleton} />
            </group>
          </group>
        </animated.group>
        </group>

        <group scale={3.4} position={[-1, 1.1, 0]} rotation={[0, Math.PI / -2, 0]}>
          <animated.group name="S3_2_Group" scale={s3_2_SpringData.scale}>
            <group name="handrig" position={[0, -1.017, 0]} scale={0.326}>
            <primitive object={nodes.root} />
            <primitive object={nodes.root001} />
            <skinnedMesh name="handmodels32" geometry={nodes.handmodels32.geometry} material={materials.Human} skeleton={nodes.handmodels32.skeleton} />
            <group name="legfibers">
              <skinnedMesh name="Cylinder001" geometry={nodes.Cylinder001.geometry} material={materials['Muscle no Texture']} skeleton={nodes.Cylinder001.skeleton} />
              <skinnedMesh name="Cylinder001_1" geometry={nodes.Cylinder001_1.geometry} material={materials['Muscle Inside']} skeleton={nodes.Cylinder001_1.skeleton} />
            </group>
          </group>
          </animated.group>
        </group>

        <group scale={1.25} rotation={[0, Math.PI / -3, 0]} position={[0, 0, 0]}>
          <animated.group name="S3_3_Group" scale={s3_3_SpringData.scale}>
            <group name="S33Armature" position={[-0.169, 0.972, -0.769]}>
              <primitive object={nodes.ArmTop_1} />
              <primitive object={nodes.ArmIK_1} />
              <primitive object={nodes.ElbowIK_1} />
              <group name="musclefibermodels33">
                <skinnedMesh name="Cylinder002" geometry={nodes.Cylinder002.geometry} material={materials['Muscle no Texture']} skeleton={nodes.Cylinder002.skeleton} />
                <skinnedMesh name="Cylinder002_1" geometry={nodes.Cylinder002_1.geometry} material={materials['Muscle Inside']} skeleton={nodes.Cylinder002_1.skeleton} />
              </group>
            </group>
          </animated.group>
        </group>

        <group position={[-.25, 0, 0]}>
          
          <animated.group name="S4_Group" scale={s4SpringData.scale}>
            <group rotation={[0, Math.PI / 6, 0]}>
              <group name="s4human_1" scale={0.01} position={[-0.846, 0, 0]} rotation={[Math.PI / 2, 0, 0]}>
                <primitive object={nodes.mixamorig1Hips_1} />
                <primitive object={nodes.elbowIKR_1} />
                <primitive object={nodes.elbowIKL_2} />
                <primitive object={nodes.handIKL_2} />
                <primitive object={nodes.handIKR_1} />
                <primitive object={nodes.headLookAt_1} />
                <primitive object={nodes.kneeIKL_1} />
                <primitive object={nodes.kneeIKR_1} />
                <primitive object={nodes.heelIKL_1} />
                <primitive object={nodes.heelIKR_1} />
        
                <skinnedMesh name="s4human_1model" geometry={nodes.s4human_1model.geometry} material={materials.Human} skeleton={nodes.s4human_1model.skeleton} />
              </group>
              <mesh name="01m" geometry={nodes['01m'].geometry} material={alwaysOnTopMaterial} />
            </group>

            <group rotation={[0, Math.PI / -6, 0]} position={[0, 0, -.25]}>
              <group rotation={[Math.PI / 2, 0, 0]} position={[0.865, 0, 0]}>
                <group name="s4human_2" scale={0.01}>
                  <primitive object={nodes.mixamorig1Hips_2} />
                  <primitive object={nodes.elbowIKR_2} />
                  <primitive object={nodes.elbowIKL_3} />
                  <primitive object={nodes.handIKL_3} />
                  <primitive object={nodes.handIKR_2} />
                  <primitive object={nodes.headLookAt_2} />
                  <primitive object={nodes.kneeIKL_2} />
                  <primitive object={nodes.kneeIKR_2} />
                  <primitive object={nodes.heelIKL_2} />
                  <primitive object={nodes.heelIKR_2} />
                  <skinnedMesh name="s4human_2model" geometry={nodes.s4human_2model.geometry} material={materials.Human_Struggle} skeleton={nodes.s4human_2model.skeleton} />
                </group>
              </group>
              <mesh name="05m" geometry={nodes['05m'].geometry} material={alwaysOnTopMaterial} />
            </group>

            <gridHelper args={[10, 10]} />
            <mesh name="Plane" rotation={[-Math.PI / 2, 0, 0]} position={[0, -0.01, 0]} scale={5}>
              <planeGeometry args={[2, 2]} />
              <meshStandardMaterial color="#000000" />
            </mesh>
          </animated.group>
        </group>

        <group scale={1.2}>
          <animated.group name="S5_Group" scale={s5SpringData.scale}>
            <mesh name="FormluaPlane" geometry={nodes.FormluaPlane.geometry} material={materials.Formula} position={[1.802, 2.587, 0.058]} scale={0.253} />
            <mesh name="Cube001" geometry={nodes.Cube001.geometry} material={materials.Graph} position={[-3.778, -1.934, 0.098]} scale={0.253} />
            <mesh name="Cube002" geometry={nodes.Cube002.geometry} material={materials.Graph} position={[-3.68, -2.032, 0.098]} rotation={[0, 0, -Math.PI / 2]} scale={0.253} />
            <mesh name="Cube003" geometry={nodes.Cube003.geometry} material={materials.Graph} position={[-3.649, -0.121, 0.098]} rotation={[0, 0, -Math.PI / 2]} scale={0.253} />
            <mesh name="Cube" geometry={nodes.Cube.geometry} material={materials.Graph_Red} position={[-3.415, -0.222, 0.098]} scale={0.231} />
            <mesh name="Cube004" geometry={nodes.Cube004.geometry} material={materials.Graph_Yellow} position={[3.778, -0.222, 0.098]} rotation={[0, 0, -Math.PI]} scale={0.231} />
            <mesh name="FormluaPlane001" geometry={nodes.FormluaPlane001.geometry} material={materials.Forta} position={[-4.295, 1.66, 0.058]} scale={0.253} />
            <mesh name="FormluaPlane002" geometry={nodes.FormluaPlane002.geometry} material={materials.fortadezvoltatademuschi} position={[-4.637, -0.138, 0.058]} scale={0.253} />
            <mesh name="FormluaPlane004" geometry={nodes.FormluaPlane004.geometry} material={materials.contractiexcentrica} position={[-2.215, 1.036, 0.058]} scale={0.253} />
            <mesh name="FormluaPlane005" geometry={nodes.FormluaPlane005.geometry} material={materials.contractieconcentrica} position={[3.595, 0.658, 0.058]} scale={0.253} />
            <mesh name="FormluaPlane007" geometry={nodes.FormluaPlane007.geometry} material={materials.fortamaximaizometrica} position={[0.608, 0.11, 0.058]} scale={0.253} />
            <mesh name="FormluaPlane008" geometry={nodes.FormluaPlane008.geometry} material={materials.contractieizometrica} position={[0.608, -1.66, 0.058]} scale={0.253} />
            <mesh name="FormluaPlane009" geometry={nodes.FormluaPlane009.geometry} material={materials.vitezadecontractieamuschiului} position={[0.595, -2.254, 0.058]} scale={0.253} />
            <group name="FormluaPlane012" position={[4.731, -1.281, 0.058]} scale={0.253}>
              <mesh name="formulamodel012" geometry={nodes.formulamodel012.geometry} material={materials.fortamica} />
              <mesh name="formulamodel012_1" geometry={nodes.formulamodel012_1.geometry} material={materials.vitezamare} />
            </group>
            <group name="FormluaPlane013" position={[4.717, -2.421, 0.058]} scale={0.253}>
              <mesh name="formulamodel014" geometry={nodes.formulamodel014.geometry} material={materials.yellowArrow} />
              <mesh name="formulamodel014_1" geometry={nodes.formulamodel014_1.geometry} material={materials.rapid} />
            </group>
            <group name="FormluaPlane015" position={[-2.727, -2.414, 0.058]} scale={0.253}>
              <mesh name="formulamodel016" geometry={nodes.formulamodel016.geometry} material={materials.redArrow} />
              <mesh name="formulamodel016_1" geometry={nodes.formulamodel016_1.geometry} material={materials.alungire} />
            </group>
            <mesh name="FormluaPlane010" geometry={nodes.FormluaPlane010.geometry} material={materials.yellowArrow} position={[3.816, -0.635, 0.058]} scale={0.253} />
            <group name="FormluaPlane003" position={[-2.313, -1.281, 0.058]} scale={0.253}>
              <mesh name="formulamodel018" geometry={nodes.formulamodel018.geometry} material={materials.fortamare} />
              <mesh name="formulamodel018_1" geometry={nodes.formulamodel018_1.geometry} material={materials.vitezamica} />
            </group>
            <mesh name="FormluaPlane006" geometry={nodes.FormluaPlane006.geometry} material={materials.redArrow} position={[-3.209, -0.635, 0.328]} rotation={[0, 0, Math.PI]} scale={0.253} />
          </animated.group>
        </group>

        <group rotation={[0, Math.PI / 1.4, 0]} position={[-1, 1, 4]}>
          <animated.group name="S6_Group" scale={s6SpringData.scale}>
            <mesh name="Bulger" geometry={nodes.Bulger.geometry} material={materials.Bulgar} position={[-0.401, 1.669, 1.03]} scale={0} />
            <group name="HumanThrow" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
              <primitive object={nodes.mixamorig1Hips_3} />
              <skinnedMesh name="humanthrowmodel" geometry={nodes.humanthrowmodel.geometry} material={materials.Human} skeleton={nodes.humanthrowmodel.skeleton} />
            </group>
            <mesh name="Baket" geometry={nodes.Baket.geometry} material={materials.Basket} position={[-0.272, 0.013, 0.358]} scale={0.458} />

            <gridHelper args={[25, 25]} />
            <mesh name="Plane" rotation={[-Math.PI / 2, 0, 0]} position={[0, -0.01, 0]} scale={13}>
              <planeGeometry args={[2, 2]} />
              <meshStandardMaterial color="#000000" />
            </mesh>
          </animated.group>
        </group>

        <group scale={1} position={[.5, 0, 0]} rotation={[0, -Math.PI / 2, 0]}>
          <animated.group name="S7_Group" scale={s7SpringData.scale}>
            <group name="s7human" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
              <primitive object={nodes.mixamorig1Hips_4} />
              <primitive object={nodes.elbowIKR_3} />
              <primitive object={nodes.elbowIKL_4} />
              <primitive object={nodes.handIKL_4} />
              <primitive object={nodes.handIKR_3} />
              <primitive object={nodes.headLookAt_3} />
              <primitive object={nodes.kneeIKL_3} />
              <primitive object={nodes.kneeIKR_3} />
              <primitive object={nodes.heelIKL_3} />
              <primitive object={nodes.heelIKR_3} />
              <skinnedMesh name="s7humanmodel" geometry={nodes.s7humanmodel.geometry} material={materials['Human.003']} skeleton={nodes.s7humanmodel.skeleton} />
            </group>
          </animated.group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./models/parghii.glb')

export default Model
