/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/tbn_burgerea.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('./models/tbn_burgerea.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cone.geometry} material={nodes.Cone.material} />
    </group>
  )
}

useGLTF.preload('./models/tbn_burgerea.glb')

export default Model;

