/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/parghii.glb 
*/

import React, { useEffect } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'
import { animated, useSpring} from '@react-spring/three';
import * as THREE from 'three'

// Custom material that always renders on top
export const alwaysOnTopMaterial = new THREE.MeshStandardMaterial({

})
alwaysOnTopMaterial.onBeforeCompile = shader => {
  shader.depthTest = false
  shader.depthWrite = false
}

export function Model_Parghii(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('./models/parghii.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions, names} = useAnimations(animations, group)

  useEffect(() => {
    actions['S1_Animation'].play();
    actions['S1_Animation'].setLoop(THREE.LoopRepeat, Infinity);
    actions['S1_Animation'].setEffectiveTimeScale(.5);

  }, [actions])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene"  position={[0, 0, 0.5]} scale={1.25}>
        <group name="S1_Human"rotation={[Math.PI / 2, 0, 0]}  position={[-0.871, 0, -0.785]}  scale={0.01}>
            <primitive object={nodes.mixamorig1Hips} />
            <primitive object={nodes.elbowIKR} />
            <primitive object={nodes.elbowIKL} />
            <primitive object={nodes.handIKL} />
            <primitive object={nodes.handIKR} />
            <primitive object={nodes.headLookAt} />
            <primitive object={nodes.kneeIKL} />
            <primitive object={nodes.kneeIKR} />
            <primitive object={nodes.heelIKL} />
            <primitive object={nodes.heelIKR} />
            <primitive object={nodes.kneeIKL001} />
            <skinnedMesh name="s1humanmodel" geometry={nodes.s1humanmodel.geometry} material={materials.Human} skeleton={nodes.s1humanmodel.skeleton} />
          </group>
          <mesh name="Stand" geometry={nodes.Stand.geometry} material={materials.Metal} scale={0.362} />
      </group>
    </group>
  )
}

useGLTF.preload('./models/parghii.glb')

export default Model_Parghii
