/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/muschi.glb 
*/

import React, { useState, useEffect } from 'react';
import * as THREE from 'three';
import { Box, OrbitControls, ScrollControls, Scroll, useScroll, Stats, Text, useGLTF, useAnimations} from '@react-three/drei';
import { animated, useSpring} from '@react-spring/three';
import { useGraph } from '@react-three/fiber'
import { SkeletonUtils } from 'three-stdlib'
import { Html } from '@react-three/drei';
import { useRef } from 'react';
import { useContext } from 'react';


function NODISPLAYMATERIAL(){
  return new THREE.MeshBasicMaterial({ visible: false });
}

function SOLIDMATERIAL(color){
  // Accepts a hex number or THREE.Color, not a string
  return new THREE.MeshBasicMaterial({ color: color || 0x000000, wireframe: false });
}

function BRAINMATERIAL(){
  const material = new THREE.MeshStandardMaterial({
    color: 0xFF6FB5,
    roughness: 0.5,
    metalness: 0.1,
  });
  return material;
}

export function MODEL_Muscles(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('./models/muschi.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions, names } = useAnimations(animations, group)

  useEffect(() => {
    if (actions['ArmatureAction']) {
      actions['ArmatureAction'].play();
    }
  }, [actions]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="musclefibermodel">
        <skinnedMesh name="Cylinder004" geometry={nodes.Cylinder004.geometry} material={materials['Muscle no Texture']} skeleton={nodes.Cylinder004.skeleton} />
        <skinnedMesh name="Cylinder004_1" geometry={nodes.Cylinder004_1.geometry} material={materials['Muscle Inside']} skeleton={nodes.Cylinder004_1.skeleton} />
      </group>
      <primitive object={nodes.Bone} />
      <mesh name="BoneForMuscle" geometry={nodes.BoneForMuscle.geometry} material={materials.Bone} scale={[1.1, .9, .9]}/>
    </group>
  );
}

useGLTF.preload('./models/muschi.glb')

export default MODEL_Muscles

